volumes:
  solr_data:
  static_files_tinx:
  certbot_var:
  certbot_acme:
services:
  tinx_ui:
    build:
      context: https://github.com/unmtransinfo/tinx-ui.git#TINX-35
    command: npm run ${BUILD_COMMAND}
    volumes:
      - static_files_tinx:/app/dist
    env_file:
      - .env
  tinx_api:
    restart: unless-stopped
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=tcrd_read_only
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./tinxapi/tinxapi/secrets.example.py:/tinx/tinxapi/tinxapi/secrets.py
    env_file:
      - .env
  nginx:
    restart: unless-stopped
    image: nginx:1
    volumes:
      - static_files_tinx:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot:/etc/letsencrypt:ro
      - certbot_acme:/var/www/certbot:ro
    ports:
      - ${TINX_NGINX_SSL_PORT:-443}:443
      - ${TINX_NGINX_HTTP_PORT:-80}:80
    depends_on:
      tinx_api:
        condition: service_started
      tinx_ui:
        condition: service_completed_successfully
    env_file:
      - .env
  mysql:
    restart: unless-stopped
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=tcrd_read_only
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=tcrd
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
    volumes:
      - ${DATABASE_VOLUME_PATH:-./db}:/var/lib/mysql
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot:/etc/letsencrypt:rw
      - certbot_var:/var/lib/letsencrypt:rw
      - certbot_acme:/var/www/:rw
      - ./certbot_logs:/var/log/letsencrypt/:rw
    command: certonly --reinstall --webroot --webroot-path=/var/www/ --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
  solr:
    restart: unless-stopped
    image: solr:6.6.6
    volumes:
      - solr_data:/var/solr
      - ./tinxapi/managed-schema:/opt/solr/server/solr/haystack/conf/managed-schema
    command:
      - solr-precreate
      - haystack
    healthcheck:
      test: ["CMD-SHELL", "! curl -s -k --max-time 14 --connect-timeout 9 https://newdrugtargets.org:8983/solr || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 2
      start_period: 5s
  solr_update_index:
    build:
      context: .
    volumes:
      - ./tinxapi/tinxapi/secrets.example.py:/tinx/tinxapi/tinxapi/secrets.py
      - ./tinxapi/managed-schema:/tinx/tinxapi/managed-schema
    command: python manage.py update_index
    depends_on:
      solr:
        condition: service_healthy
    env_file:
      - .env
  solr_update_metadata:
    build:
      context: .
    volumes:
      - ./tinxapi/tinxapi/secrets.example.py:/tinx/tinxapi/tinxapi/secrets.py
      - ./tinxapi/managed-schema:/tinx/tinxapi/managed-schema
    command: python tinxapi/metadata.py
    env_file:
      - .env
    depends_on:
      solr_update_index:
        condition: service_completed_successfully
